---
- name: Upload standard syslog-ng log file with watchdog configured
  template:
    src: watchdog-syslog-ng.j2
    dest: /etc/syslog-ng/syslog-ng.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_syslog-ng